### ISSUE TITLE
if I add a new server to the cluster with leader annotation the current connections between locations are dropped

### ISSUE THREAD

**Issue by carlosrmendes** [squat/kilo#39] opened 2020-02-26 11:52 UTC
I have a cluster in two locations, A and B, with one server on each location successfully connected with kilo.

Each server has on pod and both pods are connected to each other.

The server on location A has the `kilo.squat.ai/leader=true` annotation, but if I add a new server at location A also with this annotation, kilo elects the new server as a new leader, updating the wg configuration on the server on location B, dropping the current connection between the pod on old leader server and the pod on the server on location B.

**Comment by squat** [comment] 2020-02-26 12:25
Hi @carlosrmendes this is not a bug. The `kilo.squat.ai/leader=true` is a hint that tells Kilo which nodes to prioritize when electing a leader. Within the pool of prioritized nodes, Kilo uses another set of heuristics to elect leaders in a stable way. That is to say, imagine the following scenario:

* you have two nodes, node 1 and node 2;
* node1 is given the leader annotation and becomes leader;
* then node2 is also given the leader annotation and Kilo changed the mesh for it to become the leader

Next sceneario:
* you have two nodes, node 1 and node 2;
* node2 is given the leader annotation and becomes leader;
* then node1 is also given the leader annotation, but this time Kilo will not change the mesh; node 2 will remain the leader.

The heuristics Kilo uses for selecting leaders are based on:
* presence of leader annotation
* IP range (is it public or private)
* IP value (sorting of IPs for stable results)

I think we can close this as not a bug.

**Comment by carlosrmendes** [comment] 2020-02-26 15:02
The first scenario is what is happen to me, but I think that if node 1 is already a leader and wireguard connection to is is ok, if I annotate the node 2 also as a leader kilo must not elect it as a new leader, because it breakings the existing connections to the node-1, when the node-1 is completely healthy and functional.

**Comment by squat** [comment] 2020-02-26 15:49
Both of the scenarios I presented are how Kilo works today and it is this way by design. Otherwise, if you want to implement what you are suggesting, then we have to introduce state into the leader election process, which is tricky and not worth the trouble IMO. In general when working with networks, it is very normal for different nodes to be partitioned and have a different view of the mesh while the mesh is being bootstrapped. If we make the current state of the mesh dependent on the previous state, then we can make almost no guarantees at all about the state that any single node will come up with in the end. What happens if one pod crashes and loses the current state of who was leader and needs to calculate the leader again? Or what happens if two partitioned networks get re-joined, how do we reconcile them and whose leader do we actually keep?

The only way around this would be to put leader information into a something like etcd (or the k8s API, which itself is backed by etcd). FWIW other projects like cillium do this today, ie you run a second etcd to keep its state.

I think the better way around this today is to keep things simple and to recommend that users only apply the leader label to one node. Additionally, we can add documentation that warns that modifying leader labels can cause the mesh to change shape and interrupt existing connections.

**Comment by squat** [comment] 2020-03-04 01:21
@carlosrmendes I will close this for now since the feature is working as designed. The documentation for the annotation is located here: https://github.com/squat/kilo/blob/master/docs/annotations.md#leader. If you think of a better way to word or explain the behavior please let me know and submit a PR, I would be super happy to merge it :))))

**Closed by squat** 2020-03-04 01:21 UTC

**Comment by carlosrmendes** [comment] 2020-03-05 14:31
I agree on what you said about network mesh, so if modifying leader annotations is not recommended do you think is better to not have any leader annotations on my public nodes than have a leader annotation on all of them?

And thanks for again for your help. :)

**Comment by squat** [comment] 2020-03-05 14:35
The leader annotation is supposed to be a hint to Kilo to suggest, "hey, from all of the possible nodes, please prefer this one." So if all of the nodes have the suggestion, then the preference loses value. If there is really one preferred node for a location, then I would recommend adding the annotation there, otherwise, if all nodes with public IPs are equally valid, then I would say it's even better to not add the annotation anywhere; it means less work for you should work just as well :)
