### ISSUE TITLE
Fails to properly initialize link if previously started with default link

### ISSUE THREAD

**Issue by withinboredom** [squat/kilo#254] opened 2021-11-15 14:33 UTC
To reproduce:

1. apply CRDs and apply kilo deployment
2. delete kilo deployment
3. update deployment with `--interface=kilo1`
3. delete interface `kilo0` (`touch /etc/wireguard/kilo0.conf && wg-quick down kilo0` -- I'm not sure where the actual config lives)
4. reboot?
5. apply new deployment
6. see `kilo0` up and `kilo1` down.

**Comment by leonnicolas** [comment] 2021-11-15 21:47
Are you using kilo with the userspace WireGuard implementation? Or what manifest did you use to apply Kilo?

**Comment by withinboredom** [comment] 2021-11-18 18:17
Wireguard is running with kernel mode:

```
lsmod | grep wireguard
wireguard             212992  0
ip6_udp_tunnel         16384  1 wireguard
udp_tunnel             16384  1 wireguard
```

I applied the k3s manifests from the readme, though I was using the one with flannel support.

**Comment by leonnicolas** [comment] 2021-11-19 09:28
Do you have network connectivity aka "is Kilo working" after you changed the interface name? And can we see some logs. Only the beginning should be interesting?

And what does `sudo wg` give you on the node?

**Comment by withinboredom** [comment] 2021-11-21 23:55
I had to completely destroy the node as I would lose all network connectivity when enabling the interface, no matter what I did. It was clear I'd somehow foobar'd it up.

**Comment by squat** [comment] 2022-04-07 13:48
Closing for now since we could not reproduce and the environment was torn down. Please re-open if you are able to reproduce and share more info.

**Closed by squat** 2022-04-07 13:48 UTC
