### ISSUE TITLE
How to create kubernetes cluster with kilo?

### ISSUE THREAD

**Issue by afeiszli** [squat/kilo#74] opened 2020-09-06 12:26 UTC
This is either a documentation question, irrelevant, or just a dumb question, but I would like to see if I can use kilo for my cluster, but I think I am just not understanding something very basic. Don't we need to have our network setup before deploying the cluster? For instance if we have a worker on a home network and a master in the cloud. Don't we need a cidr for the private IP's when creating the cluster? Does kilo just provide the pod networking or the node networking as well? Because if so I'm confused how we can deploy on top of kubernetes if we need to have the vpn in place before deploying kubernetes.

**Comment by tetricky** [comment] 2020-09-17 11:47
It may be useful you to refer to my issue: https://github.com/squat/kilo/issues/76 where I have installed kilo on a cluster without (flannel) networking. Also if you refer to the instructions, it is possible to install in 'Add-on mode', with an existing networking layer in place. https://github.com/squat/kilo#add-on-mode.

I can't help you on getting much past that point, I'm still working on it myself.

**Comment by squat** [comment] 2021-03-05 16:56
Hi @afeiszli, Kilo provides both Pod-Pod networking as well as node-node networking, just like Flannel or Calico. The difference is that the nodes don't all have to be in the same data-center or connected to the same LAN. For this to work, the nodes must already have at least one Ethernet interface with an IP and the the API server endpoint _must_ be accessible before the VPN comes up. This means that the Kilo agent running on the nodes will contact the API server using a publicly accessible IP address, just like kubectl will when run from a laptop. Once Kilo contacts the API server an introspects the state of the cluster, it can begin to set up the necessary encapsulation interfaces, routes, iptables rules, etc.

I'm closing this for now since the issue is a bit old. Please re-open if you have more questions!

**Closed by squat** 2021-03-05 16:56 UTC
