### ISSUE TITLE
Peering clusters behind nat

### ISSUE THREAD

**Issue by borys569** [squat/kilo#337] opened 2022-11-10 16:41 UTC
Hi,
I have the following use case:
- one main cluster is in AWS (with public IP); (cluster A);
- multiple small clusters on the edge devices behind NAT (cluster B).

Cluster A needs access to services in NATed clusters. I was hoping to use kilo to interconnect the clusters. 
Is this document [https://kilo.squat.ai/docs/multi-cluster-services/] a correct approach considering that clusters are behind NAT? Or do I need to use a different configuration?

**Comment by squat** [comment] 2022-12-01 00:44
Hi @borys569 yes, this document is correct :) if the clusters at the edge don't need to communicate among one another but only with the cluster in the cloud, then this document is mostly correct. It will need to be modified slightly to reflect the fact that the endpoint that cluster A has to connect to cluster B will be floating. That means that cluster B will have cluster A's public IP as it's endpoint and cluster A will have floating of the cluster B peer resource endpoint value enabled by setting the persist not keepalive to a non-zero value. This will allow cluster A to discover the cluster B endpoint and allow that endpoint to float.

**Comment by stv0g** [comment] 2023-06-14 12:30
This is a duplicate of #189

**Comment by squat** [comment] 2023-06-14 13:24
Thanks @stv0g :) closing

**Closed by squat** 2023-06-14 13:24 UTC
