### ISSUE TITLE
remote VPN client

### ISSUE THREAD

**Issue by outbackdingo** [squat/kilo#40] opened 2020-02-27 12:32 UTC
ok enlighten me again! docs are sketchy .... for a vpn now that kilo is running on 3 nodes.... id like to 
connnect my remote laptop for administration and web access, where are we deriving the keys from ? i imagine this is the "client" public key ? and i can get the server/cluster side with wg showconf ? 
I do appreciate the assitance, but yes i will say docs are a bit lacking, that being said point me in the right direction, and i can help with documentation once i get the connection sorted.

VPN

Kilo also enables peers outside of a Kubernetes cluster to connect to the VPN, allowing cluster applications to securely access external services and permitting developers and support to securely debug cluster resources. In order to declare a peer, start by defining a Kilo peer resource:

cat <<'EOF' | kubectl apply -f -
apiVersion: kilo.squat.ai/v1alpha1
kind: Peer
metadata:
  name: squat
spec:
  allowedIPs:
  - 10.5.0.1/32
  publicKey: GY5aT1N9dTR/nJnT1N2f4ClZWVj0jOAld0r8ysWLyjg=
  persistentKeepalive: 10
EOF

**Comment by squat** [comment] 2020-03-04 01:14
Hi @outbackdingo, the docs are currently targeted towards users experienced in both the domains of WireGuard AND Kubernetes, so they could certainly be improved by simplifying and providing more explanation. It looks like you took that snippet from the main README; if you haven't yet, please take a look at the [vpn docs](https://github.com/squat/kilo/blob/master/docs/vpn.md) in case that gives you more context.

Nevertheless, here are more specific instructions. I would very much appreciate your help in distilling these steps into the VPN doc.

To set up a peer for the VPN you must first configure your local machine with a WireGuard link.
This means doing the following:
* locally generating a private key
* using the private key to generate a public key (these two steps should be covered by the link in the vpn doc to the WireGuard documentation's section on [key generation](https://www.wireguard.com/quickstart/#key-generation))
* creating a WireGuard network device; example on Linux: `sudo ip l add wg0 type wireguard`
* giving that WireGuard device a network address; example on Linux: `sudo ip a add dev wg0 10.5.0.1/32`
* set the WireGuard device's private key; example on Linux: `sudo wg set wg0 listen-port private-key /path/to/private-key`

Once that is done, we need to inform the cluster about our local host. We do this by creating a Peer resource via kubectl. The Peer CRD represents a WireGuard peer, ie a node in the mesh. Take the public key that was generated earlier as well as the IP address (including network prefix) and use them to create a Peer resource via kubectl:
```shell
export PEER=laptop # pick a name for your peer
cat <<EOF | kubectl apply -f -
apiVersion: kilo.squat.ai/v1alpha1
kind: Peer
metadata:
  name: $PEER
spec:
  allowedIPs:
  - 10.5.0.1/32 # IP address for the local link
  publicKey: GY5aT1N9dTR/nJnT1N2f4ClZWVj0jOAld0r8ysWLyjg= # the generated public key
  persistentKeepalive: 10
EOF
```

Once we have informed the cluster of our local machine, we must inform our machine about the cluster. This means we need to produce a WireGuard configuration for our local machine based on the information from the cluster. Kilo provides a CLI tool to help with that:
```shell
kgctl showconf peer $PEER > peer.ini
sudo wg setconf wg0 peer.ini
```

Lastly, we need to create routes on our local machine to the IPs on our cluster. If you are on macOS, this is done automatically for you; if you are on Linux, the following snippet can help:
```shell
for ip in $(kgctl showconf peer $PEER | grep AllowedIPs | cut -f 3- -d ' ' | tr -d ','); do
	sudo ip route add $ip dev wg0
done
```

Please let me know how it goes for you :)

**Comment by outbackdingo** [comment] 2020-03-04 01:59
ok, the confusing part was kgctl showconf peer $PEER > peer.ini in which i needed to git clone the repo and go build kgctl ..... also i did have to pass the kgctl --kubeconfig /home/username/.kube/config  for it to work. Lastly seems my vpn connection is up, however it appears only to route for the cluster, all other traffic is routed through my provider. looking at whatismyip i see my home ip not my vpn server ip.... seems a route is missing maybe ?

**Comment by squat** [comment] 2020-03-04 02:21
Ah I see, yes, there is a pending issue to provide prebuilt binaries for kgctl. That will make working with local interfaces easier.

Regarding VPNing to the internet: by default, Kilo doesn't set up your machine to use the cluster as a gateway to the internet, it only provides configuration for the IPs of the peers in the mesh, ie accessing Pod IP, node IPs etc. 

If you'd like to use the cluster as an internet gateway, you can manually configure it as follows:
* open the generated peer.ini file with your editor
* pick one of the peer sections in the file and add 0.0.0.0/0 to its allowedIPs section
* set the WireGuard configuration
* add a route for all IPs via your WireGuard device: `sudo ip route add 0.0.0.0/0 dev wg0`
* add a route for the public IP of the cluster's mesh nodes via your laptop's Ethernet/wifi device, otherwise you won't be able to send the encrypted and encapsulated packets to the cluster: `sudo ip route add <public IP of cluster node> dev <wifi device>`

**Comment by outbackdingo** [comment] 2020-03-04 03:25
something not right... it seems that the tunnel comes up but i cant ping anything.....

**Comment by squat** [comment] 2020-03-05 14:27
hey @outbackdingo I put together some more thorough docs for using the cluster as a VPN server to access the internet. I tested this locally with a Kilo cluster and have it working. Please test it out and we can add it to the docs :)

---

Although it is not a primary goal of the project, the VPN created by Kilo can also be used by peers as a gateway to the Internet.
In order configure a local machine to use the VPN as a gateway to the Internet, first register the local machine as a peer of the cluster following the steps in the [VPN doc](https://github.com/squat/kilo/blob/master/docs/vpn.md).

Once the machine is registered, generate the configuration for the local peer:

```shell
PEER=squat # name of the registered peer
kgctl showconf peer $PEER > peer.ini
```

Next, the WireGuard configuration must be modified to enable routing traffic for any IP via a node in the cluster.
To do this, open the WireGuard configuration in an editor, select a node in the cluster, and set the `AllowedIPs` field of that node's corresponding `peer` section to `0.0.0.0/0, ::/0`:

```shell
$EDITOR peer.ini
```

The configuration should now look something like:

```ini
[Peer]
PublicKey = 2/xU029dz/WtvMZAbnSzmhicl8U1/Y3NYmunRr8EJ0Q=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 108.61.142.123:51820
```

The configuration can then be applied to a local WireGuard interface, e.g. `wg0`:

```shell
IFACE=wg0
sudo wg setconf $IFACE peer.ini
```

Next, add routes for the public IPs of the WireGuard peers to ensure that the packets encapsulated by WireGuard are sent through a real interface:

```shell
default=$(ip route list all | grep default | awk '{$1=""; print $0}')
for ip in $(sudo wg | grep endpoint | awk '{print $2}' | sed 's/\(.\+\):[0-9]\+/\1/'); do
    sudo ip route add $ip $default
done
```

The local machine can then be configured to use the WireGuard interface as the device for the default route:

```shell
sudo ip route delete default
sudo ip route add default dev $IFACE
```

Finally, SSH onto the selected node and configure it to masquerade traffic coming from the local machine:

```shell
export IP=10.5.0.1 # the IP of the WireGuard interface of the local machine.
sudo iptables -t nat -A POSTROUTING -s $IP -j MASQUERADE
```

The local machine is now using the selected node as its Internet gateway.

**Comment by squat** [comment] 2020-03-05 17:23
PR: https://github.com/squat/kilo/pull/44

**Comment by outbackdingo** [comment] 2020-03-06 02:35
note: vpn is up now, please note the missing piece was
Finally, SSH onto the selected node and configure it to masquerade traffic coming from the local machine:

export IP=10.5.0.1 # the IP of the WireGuard interface of the local machine.
sudo iptables -t nat -A POSTROUTING -s $IP -j MASQUERADE

finally.... also for documentation
building a wg0.conf for the host by taking a generated peer.ini and appending it to wg0.conf
allows for sudo wg-quick up wg0 to build a working tunnel and setup the required rules.
example:
/etc/wireguard/wg0.conf
[Interface]
Address = 10.5.0.1/24
PrivateKey = placehostsprivatekeydatastringhere=
ListenPort = 51820

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0, 10.233.64.0/24, 10.233.0.1/32, 10.233.65.0/24, 10.233.0.1/32, 10.4.0.1/32
Endpoint = xxx.xxx.xxx.xxx/xxxxx
PersistentKeepalive = 10
PublicKey = placeendpointpublickeyhere

**Comment by squat** [comment] 2020-03-06 08:22
@outbackdingo great! I'm glad to hear it's working for you now :) Should we close the issue?

**Comment by squat** [comment] 2020-03-09 17:50
btw, I just pushed a commit that eliminates the need for the last step of SSHing onto the nodes to set a iptables rule; this is now taken care of by Kilo: https://github.com/squat/kilo/commit/7051b9fe2954e1675a1dcdc99e9b0a58ffd678aa.

I updated the docs in the PR to reflect that. I didn't hear any objection so I'll go ahead and merge. Thanks for your input throughout the issue :)

**Closed** 2020-03-09 17:57 UTC

**Comment by outbackdingo** [comment] 2020-03-09 18:36
ever heard of subspace ?? https://github.com/subspacecommunity/subspace im having a hell of a time deploying it via k8s... was curious if you could enlighten me on network=host https://github.com/subspacecommunity/subspace/issues/10 in reference to their reply ....  i think the added benefit of subspace on top of kilo woiuld be awesome, however... i think you guys might need to collaborate... i got through the kilo with your help.... maybe you can help them understand your iptables setup

**Comment by squat** [comment] 2020-03-09 19:15
never heard of subspace but it looks very cool!
regarding that issue, kubernetes absolutely allows you to put a pod in the host network, e.g.:
https://github.com/squat/kilo/blob/master/manifests/kilo-k3s.yaml#L99

Note, you will likely also need: to make the pod privileged (or at lease give it CAP_NET_ADMIN) https://github.com/squat/kilo/blob/master/manifests/kilo-k3s.yaml#L112

**Comment by outbackdingo** [comment] 2020-03-11 03:43
hrmmmm seems somethings changed.... no longer functioning.... i believe its the iptables additions... everything was working fine....

**Comment by squat** [comment] 2020-03-11 08:12
The iptables addition does exactly what you did by hand when sshing onto the node. You may need to reboot the node in order to clear the old and now duplicated rules

**Comment by outbackdingo** [comment] 2020-03-11 14:06
ok really odd... still not happy... is there maybe a syntax error in the rules being created?? also, is there a docker image tag version i can redeploy and test against prior to all these changes ?

**Comment by squat** [comment] 2020-03-11 14:16
The tag just before the VPN changes is: `squat/kilo:8908cf19cb8661b99d27ec7db92e735a7182cc51`

All commits get tagged; you can find more here: https://hub.docker.com/r/squat/kilo/tags

I wonder if it may have actually been removing a different set of rules that weren't necessary on certain nodes.

Before trying that tag, would you mind testing SSHing onto the node and testing something?
Plz try:
```shell
sudo iptables -t filter -A FORWARD -s $THE_IP_OF_YOUR_PEER  -j ACCEPT
sudo iptables -t filter -A FORWARD -d $THE_IP_OF_YOUR_PEER  -j ACCEPT
```
Where `$THE_IP_OF_YOUR_PEER` is the IP address of your laptop's WireGuard interface, e.g 10.5.0.1.

I'll try to reproduce the issue

**Comment by squat** [comment] 2020-03-13 01:30
btw @outbackdingo, I wrote a shim to enable using Subspace to manage the peers for Kilo: https://github.com/squat/kilosubspace. I'm using it right now :)

**Comment by belerweb** [comment] 2024-01-03 16:22
> The tag just before the VPN changes is: `squat/kilo:8908cf19cb8661b99d27ec7db92e735a7182cc51`
> 
> All commits get tagged; you can find more here: https://hub.docker.com/r/squat/kilo/tags
> 
> I wonder if it may have actually been removing a different set of rules that weren't necessary on certain nodes.
> 
> Before trying that tag, would you mind testing SSHing onto the node and testing something? Plz try:
> 
> ```shell
> sudo iptables -t filter -A FORWARD -s $THE_IP_OF_YOUR_PEER  -j ACCEPT
> sudo iptables -t filter -A FORWARD -d $THE_IP_OF_YOUR_PEER  -j ACCEPT
> ```
> 
> Where `$THE_IP_OF_YOUR_PEER` is the IP address of your laptop's WireGuard interface, e.g 10.5.0.1.
> 
> I'll try to reproduce the issue

That's not enough.
Must add```sudo iptables -t nat -A POSTROUTING -s $IP -j MASQUERADE``` or ```sudo iptables -t nat -A POSTROUTING -o kilo0 -j MASQUERADE``` for client.

Please review it.

**Comment by squat** [comment] 2024-01-03 17:26
Hi @belerweb, I'd happily take a look. Did you make a PR somewhere to review? Otherwise can you give me more context about who needs to add these iptables rules? Thanks for the update :tada:

**Comment by belerweb** [comment] 2024-01-04 14:15
Thanks for your quick response. My case is below:
My cluster is v1.23.4+k3s1 with kilo 0.6.0. There are two nodes NodeA and NodeB. Two nodes in two logic locations.
NodeA has public IPv4 A.A.A.A, private IPv4 a.a.a.a.
NodeB has public IPv4 B.B.B.B, private IPv4 b.b.b.b.

wg ON NodeA  show a peer NodeB. ping b.b.b.b on NodeA success. telnet b.b.b.b ports success.

Then I created a peer in kilo, and use the peer config on my laptop.
```
[Peer]
PublicKey = NodeA's public key
AllowedIPs = 0.0.0.0/0
Endpoint = A.A.A.A:51820
PersistentKeepalive = 10
```
--

My laptop can access internet (for example ping 1.1.1.1 or access www.google.com) through NodeA.
My laptop can ```ping a.a.a.a``` success.
But can't ```ping b.b.b.b```, can't telnet b.b.b.b ports.

After research, read kilo document and source code, I even try --iptables-forward-rules, but it did not worked.

At last, I try ```iptables -t nat -A POSTROUTING -o kilo0 -j MASQUERADE```, it worked. I can ```ping b.b.b.b```, telnet b.b.b.b ports success. 
The success iptables command idea come from this issue's comments(https://github.com/squat/kilo/issues/40#issuecomment-595568074_),

<br class="Apple-interchange-newline">

**Comment by belerweb** [comment] 2024-01-16 09:30
@squat Do you have time review it https://github.com/squat/kilo/issues/40#issuecomment-1877162344 ?
