### ISSUE TITLE
No IP on interface using kubeadm

### ISSUE THREAD

**Issue by LalitMaganti** [squat/kilo#70] opened 2020-08-07 01:59 UTC
Disclaimer: I've quite new to Kubernetes so bear with me if something I'm saying doesn't make sense.

Context: I've been trying out various ways of deploying Kubernetes behind NATs (e.g. spreading a cluster between my house, a friend's and a cloud provider) and kilo seems to perfectly address this usecase as Wireguard has NAT traversal built-in. Other networking points seem to lack as deep support for NAT (maybe with the exception of Weave).

Issue: No matter what I do, I cannot seem to get kilo to give an IP address to the Wireguard interface if I deploy a cluster with `kubeadm`. This is even with a single server on a public IP (so shouldn't have any NAT interference).

I do see the annotations if I do `kubectl get node -o yaml` but the config doesn't seem to be propagated to the interface and kgctl tells me: `did not find any valid Kilo nodes in the cluster` I've tried with both standalone kilo as well as integrating with flannel and neither seems to work.

However, if I instead use k3s, everything works flawlessly as I would expect. I would prefer to use `kubeadm` to get the more _bare-metal_ experience but I'm happy enough with k3s now.

Is this a known issue or could I get some extra logs to help debug this? Thanks!

**Comment by squat** [comment] 2020-08-07 07:37
Hi @tilal6991 sounds like a very cool project :)) I have some clusters/multiclusters spanning homes like this too.

If this works out of the box with k3s then I'm confident we can find a solution for kubeadm. The fact that kgctl says no valid nodes were found indicates that the the kg agents on the nodes are probably not discovering all the necessary info.

Could you please share:
* logs from a Kilo pod
* for the same node on which that pod is running, the output of `kubectl get node -o yaml`
* any extra details about the setup, eg does your kubeadm setup also use flannel?

Talk to you soon :)

**Comment by tilal6991** [comment] 2020-08-07 21:35
1. Logs from the kilo pod: https://hastebin.com/raw/vufavupewa
2. `get node` output: https://hastebin.com/raw/ruqulamaho (I've redacted my IP addresses but everything else should be there)
3. The log and node above is just running kilo standalone with no flannel - I get the same result even if I use flannel

**Comment by squat** [comment] 2020-08-08 09:14
Hi @tilal6991 from the node yaml it looks like the problem is that the nodes are not being allocated Pod CIDRs by the controller manager. Kilo requires these Pod CIDRs to be present to know how to route packets in the WireGuard mesh. By default k3s is configured to do set the Pod CIDR but it's possible that your kubeadm installation is not. Please take a look at your controller manager and ensure that the `--allocate-node-cidrs` flag is set. That should fix it!

**Comment by tilal6991** [comment] 2020-08-08 14:35
Aha that fixed it! Specifically, I specified `--pod-network-cidr=10.130.0.1/24` on the `kubeadm init` command following what is said in [1].

It may be worth documenting this in the README as it may catch new people to K8s (like myself) off by guard as the K8s documentation does not make clear that you *must* do this for CNIs to work. Up to you whether you want to leave this bug open to track the documentation change or feel free to close it otherwise.

Thanks a lot for your help!

[1] https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

**Comment by tilal6991** [comment] 2020-08-08 15:01
On further inspection, the above didn't work :/ An IP address was allocated but then CoreDNS refused to startup.  The error message from the Kilo pod was https://hastebin.com/raw/balolijola.

I also tried doing what's described here [1] and setting the config at https://pastebin.com/qYtzCkLC but this also fails with an identical log.

Unfortunately, this means I'm at a bit of a loss of what to do again :/

**Comment by squat** [comment] 2020-08-08 17:12
Hi @tilal6991 why do you say it didn't work? The logs you shared from the Kilo Pod look good to me (except for not being able to find the Peer resource). The Kilo agent says that no CNI config is present and then it sets the allocated Pod CIDR in the CNI config as expected. If you log into one of the nodes, is there any output when you run the WireGuard command, ie`wg`?

Also, is the public IP address explicitly assigned to one of the interfaces on the host? If not, then Kilo will likely not be able to discover it and you will need to manually configure the endpoint using the force-endpoint annotation.

**Comment by tilal6991** [comment] 2020-08-08 18:20
So the Wireguard part seems to be working as expected (I can see the IP address and public key etc correctly if I run `wg`) but K8s does not seem to think CNI is enabled (and CoreDNS does not come up either).

**Comment by squat** [comment] 2020-08-09 09:30
To quickly make sure that WireGuard is working completely, can you check if kgctl successfully returns when you try to generate a graph?

The issue with CNI not working completely is interesting. If you tail the kubelet logs do you see errors about creating container sandboxes? Would you mind sharing a snippet of the logs?

If you enabled the pod CIDR allocation while the cluster was running then you may need to restart the node (or at least the kubelet) to ensure the node is not in a weird state. But if this is a fresh node then this doesn't explain it.

**Comment by tilal6991** [comment] 2020-08-15 13:55
Yup `kgctl` shows the graph correctly.

Unfortunately, kubelet logs do not show anything (they are empty) and for the pod CIDR, I created the node from fresh after a reboot so there should be no conflicts.

**Comment by tilal6991** [comment] 2020-08-15 13:59
Btw if I describe the node, I do see the line:
```
  Ready            False   Sat, 15 Aug 2020 13:53:56 +0000   Sat, 15 Aug 2020 13:48:13 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
which seems suspcious.

**Comment by tilal6991** [comment] 2020-08-15 14:05
Ah actually the kubelet logs do show something (was looking in the wrong place):
```
Aug 15 14:03:54 <hostname> kubelet[17597]: W0815 14:03:54.474002   17597 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Aug 15 14:03:55 <hostname> kubelet[17597]: E0815 14:03:55.386351   17597 kubelet.go:2188] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by tilal6991** [comment] 2020-08-15 14:14
Ok I think I figured out the problem. The yaml file for kubeadm binds to the host path of `/etc/kubernetes/cni/net.d` whereas my install is looking at `/etc/cni/net.d`. I'm using Ubuntu Server 18.04 btw if that has any bearing on where paths should be.

I manaually copied the .conflist file to /etc/cni/net.d and things started moving in the kubelet logs. Specifically, now I get the error:
```
Aug 15 14:13:29 <hostname> kubelet[17597]: W0815 14:13:29.932400   17597 cni.go:331] CNI failed to retrieve network namespace path: cannot find network namespace for th
e terminated container "bd89712c3d065e17a5e941878f351267d7f383b6e093d437ca1e192672a55191"
Aug 15 14:13:29 kubeadm-test-1596899760045-s-2vcpu-2gb-lon1-01 kubelet[17597]: E0815 14:13:29.967048   17597 cni.go:385] Error deleting kube-system_coredns-66bff467f8-jwt5g/bd89712c3d065e17a5e941878f35126
7d7f383b6e093d437ca1e192672a55191 from network bridge/kilo: no IP ranges specified
Aug 15 14:13:29 <hostname> kubelet[17597]: E0815 14:13:29.968475   17597 remote_runtime.go:128] StopPodSandbox "bd89712c3d065e17a5e941878f351267d7f383b6e093d437ca1e1926
72a55191" from runtime service failed: rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod "coredns-66bff467f8-jwt5g_kube-system" network: no IP ranges specified
Aug 15 14:13:29 <hostname> kubelet[17597]: E0815 14:13:29.968556   17597 kuberuntime_manager.go:895] Failed to stop sandbox {"docker" "bd89712c3d065e17a5e941878f351267d
7f383b6e093d437ca1e192672a55191"}
Aug 15 14:13:29 <hostname> kubelet[17597]: E0815 14:13:29.968613   17597 kuberuntime_manager.go:674] killPodWithSyncResult failed: failed to "KillPodSandbox" for "f6120
21d-630c-4ea3-a4a8-9de0644c61db" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"coredns-66bff467f8-jwt5g_kube-system\" network: no IP ranges specifi
ed"
Aug 15 14:13:29 <hostname> kubelet[17597]: E0815 14:13:29.968637   17597 pod_workers.go:191] Error syncing pod f612021d-630c-4ea3-a4a8-9de0644c61db ("coredns-66bff467f8
-jwt5g_kube-system(f612021d-630c-4ea3-a4a8-9de0644c61db)"), skipping: failed to "KillPodSandbox" for "f612021d-630c-4ea3-a4a8-9de0644c61db" with KillPodSandboxError: "rpc error: code = Unknown desc = netw
orkPlugin cni failed to teardown pod \"coredns-66bff467f8-jwt5g_kube-system\" network: no IP ranges specified"
```

**Comment by infinitis** [comment] 2020-08-16 22:19
Running into the same issue using kubeadm/kubelet/kubectl v1.18.8.

**Comment by squat** [comment] 2021-03-05 16:59
I think this is now fixed by https://github.com/squat/kilo/pull/130.
Closing for now, however please re-open if you have issues. Thanks!

**Closed by squat** 2021-03-05 16:59 UTC
