### ISSUE TITLE
Crash when route event dest nil (and Kilo fails to work after crashing)

### ISSUE THREAD

**Issue by SerialVelocity** [squat/kilo#17] opened 2019-08-27 16:14 UTC
Hi squat!

I encountered a crash on latest develop (c93fa1e):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x123ae3e]

goroutine 64 [running]:
github.com/squat/kilo/pkg/route.(*Table).Run.func1(0xc000420390, 0xc00007f2c0, 0xc00007e780)
        /kilo/pkg/route/route.go:96 +0x24e
created by github.com/squat/kilo/pkg/route.(*Table).Run
        /kilo/pkg/route/route.go:80 +0x1d9
```

It happens when I run:
```
sudo systemctl restart systemd-networkd
```
The event that is breaking kilo is (with my ipv6 gateway redacted):
```
{Ifindex: 2 Dst: <nil> Src: <nil> Gw: 0123:4567:89ab:cdef:: Flags: [] Table: 254}
```
Once kilo restarts, the old interface still exists so kilo tries to create a second interface and fails miserably unless I intervene:
```
{"caller":"mesh.go:666","component":"kilo","error":"address already in use","level":"error","ts":"2019-08-27T15:31:41.993388636Z"}
```

There's two issues here:
 - The crash occurred. I guess you just need to filter out nil dst entries?
 - When a crash occurs, Kilo restarts but tries to use a new interface. That results in a lot of errors and networking not working. Is there a reason why you don't just pick `kilo0` every time?

**Comment by squat** [comment] 2019-08-27 16:37
@SerialVelocity thanks for the detailed report!
1. yes, let's filter those out, that should do the trick :)
2. what other errors do you encounter because of this? We could certainly pick `kilo0` every time, it is not a hard requirement to generate a new one, just correctness in case the iface exists for legitimate reasons

**Comment by SerialVelocity** [comment] 2019-08-28 01:18
For 2, it just prints the "address already in use` error I posted above over and over again.

I think using `kilo0` by default will increase kilo's resiliency. Some crashes are unavoidable so it's better to recover without human intervention!
If you are worried about there being legitimate reasons for needing multiple kilo devices you can always expose a flag to set the name?

**Comment by squat** [comment] 2019-09-24 14:15
This is now fixed by 20349de and 1265ce0. The cause of the crashes is removed. Furthermore, I went with your exact suggestion:
> This commit makes it possible to specify the Kilo interface name. If the
> specified interface exists, it will be used; if it does not exist, Kilo
> will create it. If the interface already existed, then it will not be
> deleted on shutdown; otherwise Kilo will destroy the interface.

**Closed by squat** 2019-09-24 14:15 UTC

**Comment by SerialVelocity** [comment] 2019-09-24 17:16
@squat You might want to consider making the "delete on shutdown" feature a flag instead (because of the first reason below). Preferably with default false given the second reason below.

Reasons for this:
 - If kilo crashes for some reason (bug, oom, etc), then the interface will be left behind. Next time kilo starts it will no longer cleanup the interface
 - When shutting down the host, restarting the DaemonSet, etc, usually you want the interface to survive otherwise you are going to be causing downtime for those services. You don't want to have to manually create the interface for that to happen.

**Comment by SerialVelocity** [comment] 2019-09-24 17:16
But thanks for fixing this! :D

**Comment by squat** [comment] 2019-09-24 17:26
I do see value in exposing this as an optional flag. However, there should be no need to manually create the interface even if kilo deletes it; the next time kilo starts up it will likewise create the interface. It is true that this will still be a slower startup than if the interface was there, as the pod needs to be started and connect to the API etc. To be honest, I went back and forth a few times on making this a flag to avoid exposing too many knobs, but it may be worth it :)
